// =============================================================================
// app_state — Estado compartido de la aplicación GUI
//
// AppState envuelve un Arc<AppStateInner> y es Clone + Send.
// Se pasa a threads de descarga/procesamiento que llaman a
// invoke_from_event_loop() para actualizar la UI.
// =============================================================================

use std::sync::{Arc, Mutex};

use slint::Weak;

use super::config_store::UserConfig;

// AppWindow is generated by slint::include_modules!() in main_gui.rs (crate root).
// We reference it via the crate root path.
use crate::AppWindow;

#[derive(Clone)]
pub struct AppState(Arc<AppStateInner>);

#[allow(dead_code)]
struct AppStateInner {
    window: Weak<AppWindow>,
    config: Mutex<UserConfig>,
    selected_file: Mutex<Option<String>>,
}

impl AppState {
    pub fn new(window: Weak<AppWindow>, config: UserConfig) -> Self {
        Self(Arc::new(AppStateInner {
            window,
            config: Mutex::new(config),
            selected_file: Mutex::new(None),
        }))
    }

    pub fn window(&self) -> Weak<AppWindow> {
        self.0.window.clone()
    }

    #[allow(dead_code)]
    pub fn config(&self) -> UserConfig {
        self.0.config.lock().unwrap().clone()
    }

    #[allow(dead_code)]
    pub fn set_config(&self, cfg: UserConfig) {
        *self.0.config.lock().unwrap() = cfg;
    }

    #[allow(dead_code)]
    pub fn selected_file(&self) -> Option<String> {
        self.0.selected_file.lock().unwrap().clone()
    }

    pub fn set_selected_file(&self, path: Option<String>) {
        *self.0.selected_file.lock().unwrap() = path;
    }

    /// Navegar a una página desde cualquier thread.
    pub fn navegar_a(&self, page: i32) {
        let window = self.window();
        slint::invoke_from_event_loop(move || {
            if let Some(w) = window.upgrade() {
                w.set_current_page(page);
            }
        })
        .ok();
    }

    /// Abrir el file picker nativo en un thread separado (rfd bloquea).
    pub fn abrir_file_picker(&self) {
        let state = self.clone();
        std::thread::spawn(move || {
            let result = rfd::FileDialog::new()
                .add_filter("Documentos", &["pdf", "png", "jpg", "jpeg", "webp", "tiff"])
                .pick_file();

            let path = result.map(|p| p.to_string_lossy().to_string());
            state.aplicar_archivo_seleccionado(path);
        });
    }

    /// Validar extensión y actualizar UI con la ruta seleccionada.
    pub fn aplicar_archivo_seleccionado(&self, path: Option<String>) {
        let es_valido = path.as_deref().map(es_extension_valida).unwrap_or(false);
        let path_str: slint::SharedString = path
            .as_deref()
            .unwrap_or("")
            .into();

        self.set_selected_file(path);

        let window = self.window();
        slint::invoke_from_event_loop(move || {
            if let Some(w) = window.upgrade() {
                w.set_selected_file(path_str);
                w.set_file_valid(es_valido);
            }
        })
        .ok();
    }
}

fn es_extension_valida(path: &str) -> bool {
    let ext = std::path::Path::new(path)
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_lowercase());
    matches!(
        ext.as_deref(),
        Some("pdf" | "png" | "jpg" | "jpeg" | "webp" | "tiff")
    )
}
